import turtle
import time as T
t = turtle.Turtle()
w = turtle.Screen()
t.shape("turtle")
t.speed(0)
w.title("workshop_basics")
t.color("red","green")
t.pensize(3)
t.speed(0)
w.bgcolor("green")
t.right(90)
t.up()
t.fd(100)
t.down()
t.left(90)
t.circle(100)
t.left(90)

for i in range (24):
    t.fd(100)
    t.right(15)
    t.bk(100)
t.fd(200)
for i in range (4):
    t.forward(100)
    t.left(90)
t.hideturtle()
t.showturtle()
t.fillcolor("red")
t.left(90)
t.fd(200)
t.circle(20,360,1000)
t.end_fill()
T.sleep(10)