import time
import turtle
def rectangle(color):
    t.begin_fill()
    t.fillcolor(color)
    for i in range (2):
        t.forward(400)
        t.right(90)
        t.forward(100)
        t.right(90)
    t.end_fill()
t=turtle.Turtle()
t.up()
t.goto(0,-300)
t.down()
t.pensize(10)
t.goto(0,400)
t.pensize(3)
rectangle("orange")
t.goto(0,300)
t.forward(200)
t.color("blue")
t.circle(-50)
t.right(90)
for i in range (24):
    t.fd(50)
    t.right(15)
    t.bk(50)
t.color("black")
t.left(90)
t.forward(200)
t.right(90)
t.forward(100)
t.right(90)
t.forward(400)
t.right(90)
t.forward(100)
t.right(90)
t.goto(0,200)
rectangle("green")
t.hideturtle()
time.sleep(10)